cask "frame" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '2.1.1'
  sha256 "57b521ffc7d9c6a1c52cfff7424edf8b1d45b664ddb54989bf025eaa37909889"

  url "https://github.com/tvanreenen/frame/releases/download/v#{version}/Frame-v#{version}.zip"
  name "Frame"
  desc "Intuitive, keyboard-driven window management for macOS."
  homepage "https://github.com/tvanreenen/frame"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/Frame-v#{version}/bin/frame"
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{appdir}/Frame.app"
  end

  app "Frame-v#{version}/Frame.app"
  binary "Frame-v#{version}/bin/frame"
end
