cask "frame" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '2.0.0'
  sha256 "f961d6e159d30805ed00b3e6fa597535ce499fa62b86f76554e0f007dea12336"

  url "https://github.com/tvanreenen/frame/releases/download/v#{version}/Frame-v#{version}.zip"
  name "Frame"
  desc "Intuitive, keyboard-driven window management for macOS."
  homepage "https://github.com/tvanreenen/frame"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/Frame-v#{version}/bin/frame"
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{appdir}/Frame.app"
  end

  app "Frame-v#{version}/Frame.app"
  binary "Frame-v#{version}/bin/frame"
end
