cask "frame" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version '3.1.1'
  sha256 "30d6b5ae39d0ec9b05b25e8318ea21c15b8a0afc773b03af832e13e98584bd34"

  url "https://github.com/tvanreenen/frame/releases/download/v#{version}/Frame-v#{version}.zip"
  name "Frame"
  desc "Intuitive, keyboard-driven window management for macOS."
  homepage "https://github.com/tvanreenen/frame"

  depends_on macos: ">= :ventura" # macOS 13

  postflight do
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{staged_path}/Frame-v#{version}/bin/frame"
    system "/usr/bin/xattr", "-dr", "com.apple.quarantine", "#{appdir}/Frame.app"
  end

  app "Frame-v#{version}/Frame.app"
  binary "Frame-v#{version}/bin/frame"
end
